name: image
version: 1.1.19
author: Brendan Duncan <brendanduncan@gmail.com>
description: Provides server and web apps the ability to load, manipulate, and save images with various image file formats including PNG, JPEG, GIF and WebP.
homepage: https://github.com/brendan-duncan/image
documentation: https://github.com/brendan-duncan/image/wiki
dependencies:
  archive: '>=1.0.16 <1.1.0'
  xml: '>=0.9.5 <1.0.0'
dev_dependencies:
  crypto: '>=0.9.0 <1.0.0'
  unittest: any
