name: GD
author: Brendan Duncan
version: 1.0.0
description: The GD library aims to provide similar functionality for server-side programs that the PHP GD library provides for image io and manipulation.  It can encode/decode various image formats and provides basic image drawing and manipulation functions.
