name: image
author: Brendan Duncan <brendanduncan@gmail.com>
version: 1.0.5
homepage: http://bitbucket.org/brendan_duncan/dart_image
description: The image library aims to provide server-side programs the ability to load, manipulate, and save various image file formats.  *previously called dart_image*
dependencies:
  archive: '>=1.0.5'
  xml: any
dev_dependencies:
  unittest: any
