name: image
author: Brendan Duncan <brendanduncan@gmail.com>
version: 1.1.3
homepage: http://bitbucket.org/brendan_duncan/image
description: Provides server and web apps the ability to load, manipulate, and save images with various image file formats.  *previously called dart_image*
documentation: https://bitbucket.org/brendan_duncan/image/wiki/Home
dependencies:
  archive: '>=1.0.6'
  xml: any
dev_dependencies:
  unittest: any
